### ISSUE TITLE
"checkYoSelf" should probably default to true.

### ISSUE THREAD

**Issue by matthewmueller** [component/closest#1]
I don't think I've ever not written this line of code. Example:

```
var target = e.target;
var p = 'P' == target.nodeName || closest(target, 'p');
```

**Comment by jonathanong** [comment]
Sure why not. Just major bump just in case

**Comment by matthewmueller** [comment]
done. https://github.com/component/closest/commit/ea5e19ca0766b40b86eb4997ca21e5fe2d000475

don't have access to bump the npm version, so do you mind doing that for me? or giving me access? 

```
npm owner add mattmueller component-closest
```

**Comment by jonathanong** [comment]
done
